name: FeatherCampfire
version: '${project.version}'
main: com.zerek.feathercampfire.FeatherCampfire
api-version: 1.19
authors: [ Zerek ]
description: Changes the default placement of campfire to unlit.
